---

- name: PLAY 1 - DEPLOYING SNMP CONFIGURATIONS ON IOS
  hosts: ios
  connection: ansible.netcommon.network_cli
  gather_facts: false

  tasks:

    - name: TASK 1 in PLAY 1 - ENSURE SNMP COMMANDS EXIST ON IOS DEVICES
      cisco.ios.ios_config:
        commands:
          - snmp-server community ntc-course RO
          - snmp-server location NYC_HQ
          - snmp-server contact JOHN_SMITH